# Generated by YCM Generator at 2018-11-22 11:19:52.951403

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-std=c++11',
    '-x', 'c++',
    #'-stdlib=libc++',
    '-DDEBUG',
    '-Wall',
    '-Wextra',
    '-Werror',
    #'-Wshadow',
    #'-DACADOS_WITH_HPMPC',
    #'-DACADOS_WITH_QPDUNES',
    #'-DACADOS_WITH_QPOASES',
    #'-DALIGNMENT=64',
    #'-DBLASFEO',
    #'-DEXT_DEP',
    #'-DLA=HIGH_PERFORMANCE',
    #'-DLA_HIGH_PERFORMANCE',
    #'-DLINUX',
    #'-DMEASURE_TIMINGS',
    #'-DMIN_KERNEL_SIZE=2',
    #'-DOS_LINUX',
    #'-DREF_BLAS_NONE',
    #'-DTARGET=GENERIC',
    #'-DTARGET_C99_4X4',
    #'-DTARGET_GENERIC',
    #'-DUSE_ACADOS_TYPES',
    #'-DUSE_C99_MATH',
    #'-D__FULL_LOGGING__',
    #'-D__NO_COPYRIGHT__',
    #'-D__NO_STATIC__',
    #'-D__SUPPRESSANYOUTPUT__',
    '-I/home/sot7rng/code/acados',
    #'-I/home/sot7rng/code/acados/external',
    '-I/home/sot7rng/code/acados/external/blasfeo/include',
    '-I/home/sot7rng/code/acados/external/hpipm/include',
    #'-I/home/sot7rng/code/acados/external/qore',
    '-I/home/sot7rng/code/acados/external/qore/KKTPACK_DENSE/include',
    '-I/home/sot7rng/code/acados/external/qore/KKTPACK_DENSE/source',
    '-I/home/sot7rng/code/acados/external/qore/QPCORE/include',
    '-I/home/sot7rng/code/acados/external/qore/QPSOLVER_DENSE/include',
    '-I/home/sot7rng/code/acados/external/qore/QPSOLVER_DENSE/source',
    #'-I/home/sot7rng/code/acados/external/qpdunes/externals/qpOASES-3.0beta',
    '-I/home/sot7rng/code/acados/external/qpdunes/externals/qpOASES-3.0beta/include',
    '-I/home/sot7rng/code/acados/external/qpdunes/include',
    #'-I/home/sot7rng/code/acados/external/qpdunes/include/qp',
    #'-I/home/sot7rng/code/acados/external/qpdunes/interfaces',
    #'-I/home/sot7rng/code/acados/external/qpdunes/interfaces/mpc',
    '-I/home/sot7rng/code/acados/external/qpoases/include',
    '-I/home/sot7rng/code/acados/external/casadi-py36-v3.4.0-64bit/casadi/include',
    '-I/home/sot7rng/code/acados/interfaces',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = '/home/sot7rng/code/acados/build'
# compilation_database_folder = ''

if os.path.exists(compilation_database_folder):
    database = ycm_core.CompilationDatabase(compilation_database_folder)
else:
    database = None

SOURCE_EXTENSIONS = ['.C', '.cpp', '.cxx', '.cc', '.c', '.m', '.mm']


def DirectoryOfThisScript():
    return os.path.dirname(os.path.abspath(__file__))


def MakeRelativePathsInFlagsAbsolute(flags, working_directory):
    if not working_directory:
        return list(flags)
    new_flags = []
    make_next_absolute = False
    path_flags = ['-isystem', '-I', '-iquote', '--sysroot=']
    for flag in flags:
        new_flag = flag

        if make_next_absolute:
            make_next_absolute = False
            if not flag.startswith('/'):
                new_flag = os.path.join(working_directory, flag)

        for path_flag in path_flags:
            if flag == path_flag:
                make_next_absolute = True
                break

            if flag.startswith(path_flag):
                path = flag[len(path_flag):]
                new_flag = path_flag + os.path.join(working_directory, path)
                break

        if new_flag:
            new_flags.append(new_flag)
    return new_flags


def IsHeaderFile(filename):
    extension = os.path.splitext(filename)[1]
    return extension in ['.H', '.h', '.hxx', '.hpp', '.hh']


def GetCompilationInfoForFile(filename):
    # The compilation_commands.json file generated by CMake does not have entries
    # for header files. So we do our best by asking the db for flags for a
    # corresponding source file, if any. If one exists, the flags for that file
    # should be good enough.
    if IsHeaderFile(filename):
        basename = os.path.splitext(filename)[0]
        for extension in SOURCE_EXTENSIONS:
            replacement_file = basename + extension
            if os.path.exists(replacement_file):
                compilation_info = database.GetCompilationInfoForFile(
                    replacement_file)
                if compilation_info.compiler_flags_:
                    return compilation_info
        return None
    return database.GetCompilationInfoForFile(filename)


def FlagsForFile(filename, **kwargs):
    if database:
        # Bear in mind that compilation_info.compiler_flags_ does NOT return a
        # python list, but a "list-like" StringVec object
        compilation_info = GetCompilationInfoForFile(filename)
        if not compilation_info:
            return None

        final_flags = MakeRelativePathsInFlagsAbsolute(
            compilation_info.compiler_flags_,
            compilation_info.compiler_working_dir_)

    else:
        relative_to = DirectoryOfThisScript()
        final_flags = MakeRelativePathsInFlagsAbsolute(flags, relative_to)

    return {
        'flags': final_flags,
        'do_cache': True
    }
